
export interface AddAsset{
         serviceName: string,
         description: string,
         make: string,
         model: string,
         year: string,
         modelNumber: string,
         imageUrl: string,
         trackerId: string,
         isAvailable: true,
         serialNumber: string,
         identificationNumber: string,
         referenceNumber1: string,
         referenceNumber2: string,
         referenceNumber3: string,
         unitCostPrice: string,
         averagePrice: string,
         standardDiscount: string,
         supplierId: number,
         frontViewImage: any,
         leftViewImage: any,
         rightViewImage: any,
         rearViewImage: any,
         topViewImage: any,
         interiorViewImage: any,
         paymentGateway: string,
          paymentReference: string,
          centreId: string,
          paymentType: string,
          bookingAmount: string,
          bookingAddress: string,
          bookingState: string,
          appointmentDate: string,
          appointmentTime: string,
          profileId: string | undefined,
          serviceId: string,
          providerId: string

}
